package com.ingsw.backend.enumeration;

public enum Category {
    ARCHEOLOGIA_E_STORIA_NATURALE,
    ARTE,
    ARTE_ASIATICA_E_TRIBALE,
    AUTO_D_EPOCA_MOTO_D_EPOCA_E_AUTOMOBILIA,
    CIMELI_MILITARI_E_DOCUMENTI_STORICI,
    DECORAZIONI_D_INTERNI,
    GIOCATTOLI_E_MODELLINI,
    GIOIELLI_E_PIETRE_PREZIOSE,
    INTRATTENIMENTO_CARTE_E_VIDEOGIOCHI,
    LIBRI_E_FUMETTI,
    MODA,
    MONETE_E_FRANCOBOLLI,
    MUSICA_E_FOTOCAMERE,
    OROLOGI_DA_POLSO,
    SPORT,
    VINI_E_DISTILLATI
}
