package com.ingsw.dietiDeals24.enumeration;

public enum Category {
    ARCHAEOLOGY_AND_NATURAL_HISTORY,
    ART,
    ASIAN_AND_TRIABAL_ART,
    VINTAGE_CARS_VINTAGE_MOTORCYCLES_AND_AUTOMOBILIA,
    MILITARY_MEMORABILIA_AND_HISTORICAL_DOCUMENTS,
    INTERIOR_DECORATIONS,
    TOYS_AND_MODELS,
    JEWELRY_AND_PRECIOUS_STONES,
    ENTERTAINMENT_CARDS_AND_VIDEOGAMES,
    BOOKS_AND_COMICS,
    FASHION,
    COINS_AND_STAMPS,
    MUSIC_AND_CAMERAS,
    WRISTWATCHES,
    SPORTS,
    WINES_AND_SPIRITS,
    SERVICES
}
